[project]
name = "external_tts_orpheus"
version = "0.0.0"
requires-python = ">= 3.11, < 3.12"
dependencies = [
    "accelerate",
    "snac",
    "transformers",
    "external_tools",
]

[tool.uv.sources]
external_tools = { path = "../../external_tools", editable = true }
