[main]
output_folder = "outputs"
queue_addr = "tcp://*:34970"

[runner]
threads = 2

[runner.submitit]
slurm = true
partition = "kyutai"
max_gpus = 1
gpus_per_task = 1
mem_per_gpu = 0
time = 1440


[asr]
provider = "whisper_hf"

[asr.whisper_hf]
model_name = "openai/whisper-large-v3"

[tts.dsm_tts_rc]
command = ["uv", "run", "external_tts_moshi.py"]
cwd = "external_tts/moshi"
max_batch_size = 32
supported_languages = ["fr", "en"]

[tts.chatterbox_full_maxturns_1]
command = ["uv", "run", "external_tts_chatterbox.py", "--max-turns=1"]
cwd = "external_tts/chatterbox"
max_batch_size = 1
supported_languages = ["en"]

[tts.base_orpheus_full_maxturns_1_c0]
command = ["uv", "run", "external_tts_orpheus.py", "--max-turns=1", "--context=0"]
cwd = "external_tts/orpheus"
max_batch_size = 1
supported_languages = ["en"]

[tts.base_dia_c0_t1]
command = ["uv", "run", "external_tts_dia.py", "-c", "0", "-t", "1"]
cwd = "external_tts/dia"
max_batch_size = 1
supported_languages = ["fr", "en"]

[tts.csm_mad30_c0_default]
command = ["uv", "run", "external_tts_csm.py", "-d", "20.", "-c", "0", "-s", "default"]
cwd = "external_tts/csm"
max_batch_size = 1
supported_languages = ["en"]

[tts11.eleven_multilingual_v2]
model_id = "eleven_multilingual_v2"
active = false

[tts11.eleven_flash_v2_5]
model_id = "eleven_flash_v2_5"
active = false

[dataset]
datasets = ["ntrex_n15_eng", "ntrex_n15_fra", "synth_dialogs_n8_fr", "synth_dialogs_n9_en"]
